### signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "userType": "CUSTOMER",
  "name":"테스트1",
  "email":"test1@gmail.com", 
  "phoneNumber": "010-1234-5678",
  "password":"test1234"
}

### signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email":"test1@gmail.com", 
  "password":"test1234"
}

### signout
POST http://localhost:3000/auth/signout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6IkNVU1RPTUVSIiwibmFtZSI6Iu2FjOyKpO2KuDEiLCJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDEwLTEyMzQtNTY3OCIsImlhdCI6MTcyNDI0NDU0OSwiZXhwIjoxNzI0MjgwNTQ5fQ.KVH302VU6vxNVkvH9ZQAzPNuO6P9t_792qCwETTlJ6w

### refresh
POST http://localhost:3000/auth/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6IkNVU1RPTUVSIiwibmFtZSI6Iu2FjOyKpO2KuDEiLCJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDEwLTEyMzQtNTY3OCIsImlhdCI6MTcyNDI0NDgzOCwiZXhwIjoxNzI0MjgwODM4fQ.pCusAcFsB6KK5SQpizcwAc7CPvE--kb_pZek-lj0J4Y
Content-Type: application/json
  
{
  "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MjQyNDQ4MzgsImV4cCI6MTcyNDg0OTYzOH0.blIL3BwVn65pWarZAfJ7PAJVYKobWxWy5f8oNxwAS68"
}