### signup
POST https://qa-moving-backend.onrender.com/auth/signup
Content-Type: application/json

# {
#   "userType": "CUSTOMER",
#   "name":"테스트1",
#   "email":"test1@gmail.com", 
#   "phoneNumber": "010-1234-5678",
#   "password":"test1234"
# }

{
  "userType": "MOVER",
  "name":"테스트20",
  "email":"test20@gmail.com", 
  "phoneNumber": "010-1234-5678",
  "password":"test1234"
}

### signin
POST https://qa-moving-backend.onrender.com/auth/signin
Content-Type: application/json

{
  "email":"test1@gmail.com", 
  "password":"test1234"
}

### signout
POST http://localhost:3000/auth/signout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6IkNVU1RPTUVSIiwibmFtZSI6Iu2FjOyKpO2KuDEiLCJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDEwLTEyMzQtNTY3OCIsImlhdCI6MTcyNTE0NTk3OSwiZXhwIjoxNzI1MTQ5NTc5fQ.ONnWeikUIkmK6V2fnFWjbheCszSrAoHyRzckAFU3x6Y

### refresh
POST http://localhost:3000/auth/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6IkNVU1RPTUVSIiwibmFtZSI6Iu2FjOyKpO2KuDEiLCJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDEwLTEyMzQtNTY3OCIsImlhdCI6MTcyNTE0NTk3OSwiZXhwIjoxNzI1MTQ5NTc5fQ.ONnWeikUIkmK6V2fnFWjbheCszSrAoHyRzckAFU3x6Y
Content-Type: application/json
  
{
  "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MjQ1OTc1NzQsImV4cCI6MTcyNTIwMjM3NH0.72Pho6hGWliWVBk7v4uMmnbFC1gDJYi37E1DtETjXZY"
}