### 이사 전문가의 리뷰 목록 조회
GET http://localhost:3000/movers/f25bd2a2-3253-4d57-9db4-9117816289ef/reviews?page=1&size=3

### 일반 소비자의 리뷰 목록 조회
GET http://localhost:3000/reviews?page=1&size=6&filterBy=pendingReview
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6IkNVU1RPTUVSIiwibmFtZSI6Iu2FjOyKpO2KuDEiLCJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDEwLTEyMzQtNTY3OCIsImlhdCI6MTcyNjEyNzU3NiwiZXhwIjoxNzI2MTMxMTc2fQ.Yb-wUeMmSzLwQT3SqDd0YxqM2srS7EyKp9s-weZpoSA

### 일반 소비자의 리뷰 등록
POST http://localhost:3000/reviews
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6IkNVU1RPTUVSIiwibmFtZSI6Iu2FjOyKpO2KuDEiLCJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDEwLTEyMzQtNTY3OCIsImlhdCI6MTcyNjEyNzU3NiwiZXhwIjoxNzI2MTMxMTc2fQ.Yb-wUeMmSzLwQT3SqDd0YxqM2srS7EyKp9s-weZpoSA
content-type: application/json

{
  "estimateId": "4ad24459-e036-4d62-b01d-0d06ea175838",
  "rating": 5,
  "comment": "이사를 정말 잘해주셨어요. 감사합니다."
}

### 일반 소비자의 리뷰 수정
PUT http://localhost:3000/reviews/5075504e-1a42-4ee1-9898-aaf710b42826
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6IkNVU1RPTUVSIiwibmFtZSI6Iu2FjOyKpO2KuDEiLCJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDEwLTEyMzQtNTY3OCIsImlhdCI6MTcyNjEyNzU3NiwiZXhwIjoxNzI2MTMxMTc2fQ.Yb-wUeMmSzLwQT3SqDd0YxqM2srS7EyKp9s-weZpoSA
content-type: application/json

{
  "rating": 4,
  "comment": "이사를 잘 해주셨어요. 감사합니다."
}

### 일반 소비자의 리뷰 삭제
DELETE http://localhost:3000/reviews/5075504e-1a42-4ee1-9898-aaf710b42826
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6IkNVU1RPTUVSIiwibmFtZSI6Iu2FjOyKpO2KuDEiLCJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDEwLTEyMzQtNTY3OCIsImlhdCI6MTcyNjEyNzU3NiwiZXhwIjoxNzI2MTMxMTc2fQ.Yb-wUeMmSzLwQT3SqDd0YxqM2srS7EyKp9s-weZpoSA
