### 모든 유저 정보 조회
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6IkNVU1RPTUVSIiwibmFtZSI6Iu2FjOyKpO2KuDEiLCJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDEwLTEyMzQtNTY3OCIsImlhdCI6MTcyNDA0OTkyMiwiZXhwIjoxNzI0MDUzNTIyfQ.Y_DSfDWz-fJZjAaRoo1e3q9QJZ9nV-_Yqm8wzX08wdU

### 유저 정보 조회
GET http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6IkNVU1RPTUVSIiwibmFtZSI6Iu2FjOyKpO2KuDEiLCJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDEwLTEyMzQtNTY3OCIsImlhdCI6MTcyNDU5NzU3NCwiZXhwIjoxNzI0NjAxMTc0fQ.WL0WqFDX9EVN6O5YNCj1S-eYvXgClXgeV70H3VTNTmw