### 모든 유저 정보 조회
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6IkNVU1RPTUVSIiwibmFtZSI6Iu2FjOyKpO2KuDEiLCJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDEwLTEyMzQtNTY3OCIsImlhdCI6MTcyNDA0OTkyMiwiZXhwIjoxNzI0MDUzNTIyfQ.Y_DSfDWz-fJZjAaRoo1e3q9QJZ9nV-_Yqm8wzX08wdU

### 유저 정보 조회
GET http://localhost:3000/users/836315c7-d392-43a6-92a6-ec2d62798801
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVHlwZSI6IkNVU1RPTUVSIiwibmFtZSI6Iu2FjOyKpO2KuDEiLCJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDEwLTEyMzQtNTY3OCIsImlhdCI6MTcyNDA0OTkyMiwiZXhwIjoxNzI0MDUzNTIyfQ.Y_DSfDWz-fJZjAaRoo1e3q9QJZ9nV-_Yqm8wzX08wdU